### ISSUE TITLE
Bug: User list missing

### ISSUE THREAD

**Issue by cameroneickmeyer** [cameroneickmeyer/ClubExcellence#10]
The User List is missing from the left navigation. Is that because this is the test environment? Filing as a bug just in case

**Comment by sn-np** [comment]
The User List was replaced with the CX Access List, where we have added the profile information for club excellence users.

Looking at it now, I see that the User List gave CX Admins access to the account information for every portal user.  I can't really see why this is necessary, but since it was an existing feature not mentioned in the spec we'll add the access back.

**Comment by sn-np** [comment]
Access added.
